# Note: Command line arguments will override the config file
# Default values from the paper are set here

# room_description: The main prompt for a new scene generation
# If None, the room geometry will be populated by the VLM according to the room description
room:
  room_description: "A small living room with a l-shape desk with a chair. The desk have a monitor and keyboard on top. There is a painting near the desk and a wall shelf with a plant on top."
  vertices: null
  door_location: null
  height: null
  window_locations: null

# Execution mode and object processing settings
# use_scene_motifs: (ablation) Use scene motifs
# use_solver: (ablation) Use DFS solver
# enable_spatial_optimization: (ablation) Enable scene level spatial optimization
# object_types: Specify which object types to generate in this run
# extra_types: Specify which extra objects to generate
mode:
  use_scene_motifs: true
  use_solver: true
  enable_spatial_optimization: true
  object_types: ["large", "ceiling", "wall", "small"]
  extra_types: ["large", "ceiling", "wall", "small"]

# Execution settings
execution:
  result_dir: "results/single_run"

# Generation parameters
# max_iterations: Maximum number of iterations to stop
# target_occupancy_percent: Target surface saturation percentage to stop iterations
parameters:
  large_object_generation:
    max_iterations: 2
    target_occupancy_percent: 75.0
  wall_object_generation:
    max_iterations: 1
    target_occupancy_percent: 50.0
  ceiling_object_generation:
    max_iterations: 1
    target_occupancy_percent: 50.0
  small_object_generation:
    max_iterations: 1
    target_occupancy_percent: 50.0 