name: hsm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy<2
  - matplotlib
  - pyyaml
  - pyrender
  - natsort
  - omegaconf

  # For GPT
  - openai
  - python-dotenv

  # For Trimesh
  - trimesh=4
  - scipy
  - pillow
  - rtree
  - shapely
  
  # For CLIP
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - regex
  - tqdm

  # For more intelligent object retrieval
  - open-clip-torch

  - pip:
    - git+https://github.com/openai/CLIP.git

    - huggingface-hub

    # For trimesh collision detection and raycasting
    - python-fcl
    - manifold3d
    - embreex

    - earcut
    - compress_json
